// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrkbrjyyvtmphpndhlyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impya2Jyanl5dnRtcGhwbmRobHljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0Mjc3MjcsImV4cCI6MjA3MzAwMzcyN30.ob6S9u47jC-eoFnWTQN6ZFgxHNMLiXAj7YgGANLZxDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});